# SPDX-FileCopyrightText: 2020 Serokell <https://serokell.io/>
#
# SPDX-License-Identifier: MPL-2.0

resolver: lts-17.4
packages: [.]

extra-packages:
  # Hedgehog with fixes for GHC 9
  - hedgehog-1.0.5
